spring:
  datasource:
    url: jdbc:mysql://localhost:3307/mumu_mall_prod?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 592295lxc
  redis:
    host: 10.16.68.188
    port: 6379
    password:
server:
  port: 8081
  address: 0.0.0.0
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.liuxinchi.mumu_mall.model.pojo

file:
  upload:
    dir: /home/liuxinchi/data/project/mumu_mall/upload
    ip: 10.16.68.188
