spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/mumu_mall?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 592295lxc
  redis:
    host: 10.16.68.188
    port: 6379
    password:
  profiles:
    active:
server:
  port: 8083
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.liuxinchi.mumu_mall.model.pojo

file:
  upload:
    dir: D:\Projects\mumu_mall\upload\
    ip: 127.0.0.1
