spring:
  datasource:
    url: jdbc:mysql://10.16.68.188:3306/mumu_mall?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 592295lxc
server:
  port: 8081
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.liuxinchi.mumu_mall.model.pojo